### PR TITLE
Update Client Data everytime the heartbeat packet is sent

### PR DESCRIPTION
**Pull request by XFuryMCPE**

### CODE REVIEW

**Comment by PeratX** [comment]
Already is

**Comment by XFuryMCPE** [comment]
No it isn't? @PeratX it doesn't update without that change unless a new client connects

**Comment by Guillaume351** [comment]
It is only updated on Nemisys server, it doesn't resend client data to other clients.

**Comment by SleepSpace9** [comment]
Can confirm this, update of clientdata by heartbeat only works with this PR!

**Pull request closed without merging**
