### PR TITLE
Add "Plus one max count" feature

### PR DESCRIPTION
**Pull request by XFuryMCPE**
allows you to make your max player count show as one plus your total player count

### CODE REVIEW

**Comment by dktapps** [comment]
I thought you were going to learn GIT so we didn't keep having to have this discussion? _Squash your commits_ (^_^)

**Comment by XFuryMCPE** [comment]
Lol i tried xd

**Comment by ZedCee** [comment]
So you tried something like this and a few others?

https://try.github.io/

**Comment by Muqsit** [comment]
What about the "squash and merge" feature, @dktapps ? lol

**Comment by dktapps** [comment]
@Muqsit I'm aware of it. But that encourages noobs to continue being noobs, instead of learning.

(By being awkward we hope to teach people _not_ to use the web editor. The way I review a PR is to look for any excuse to reject it. If I can't find a reason to reject it, then the author has done a good job.)

**Comment by XFuryMCPE** [comment]
Most ppl that use Genisys don't know how to use git (true fact) just squash and merge it, i really don't want to learn git when github web is way easier lol

**Comment by dktapps** [comment]
@XFuryMCPE Difference is, people that _use_ Genisys don't need to learn to use GIT, since they are only _using_ it. However, if you want to contribute, you follow our rules. And if you won't learn, then your contributions will not be accepted.

(If there's one thing I can't tolerate, it's people who refuse to use their brains and learn.)

**Comment by XFuryMCPE** [comment]
Well then just close it even though many people would like it. :(

**Comment by xZeroMCPE** [comment]
This PR is useless though.......

**Comment by dktapps** [comment]
Well, if you're too lazy to fix it, it gets closed.

**Comment by XFuryMCPE** [comment]
no one asked your dumbass @xZeroMCPE , if its useless then don't say anything and go.

**Comment by xZeroMCPE** [comment]
@XFuryMCPE  Says the dumbase😂
still immature 😂😂

**Comment by dktapps** [comment]
En mi opinión there's no bigger dumbass than one who refuses to learn.

**Pull request closed without merging**
