### PR TITLE
Possible, that fixed https://github.com/iTXTech/Nemisys/issues/26

### PR DESCRIPTION
**Pull request by tarik02**
Fixed "Too many open files". This requires some testers.

### CODE REVIEW

**Comment by XFuryMCPE** [comment]
Testing this right now!

**Comment by Tarik02** [comment]
This helps, nemisys now can work more than 24 hours without reboots and freezing, so I can write strong +.

**Comment by Tarik02** [comment]
This helps, i'm tested nemisys with players, working more tan 24 hours, so i can say strong +.

**Comment by tarik02** [comment]
This not helps.

**Comment by XFuryMCPE** [comment]
Lets remove the server log altogether. It's very unnecessary.

**Comment by tarik02** [comment]
@XFuryMCPE, i will create PR with that.

**Comment by xZeroMCPE** [comment]
@Tarik02  Server logs is useless based on my opinion lol. It should be removed.

**Comment by XFuryMCPE** [comment]
Great!

**Comment by XFuryMCPE** [comment]
I also think the server log could slow down server performance, constantly writing to the log file.

**Pull request closed without merging**
