### PR TITLE
Remove timeout

### PR DESCRIPTION
**Pull request by XFuryMCPE**
#49? Players don't timeout anymore with this

### CODE REVIEW

**Comment by tarik02** [comment]
-1

**Comment by dktapps** [comment]
@Tarik02 If you're going to say things like that, at least explain _why_ you're not happy with it.

**Comment by xZeroMCPE** [comment]
-1

**Comment by DaMatrix** [comment]
+1. A lot of my players are constantly getting kicked off from "timeout".

**Comment by dktapps** [comment]
@DaMatrix thank you, at least somebody knows what "reasons" are.

**Comment by SleepSpace9** [comment]
@XFuryMCPE Did you already test it? Doesn't Genisys also has to be changed? => https://github.com/iTXTech/Genisys/blob/master/src/synapse/Player.php#L260

**Comment by XFuryMCPE** [comment]
Yeah that needs to be updated too, that can be done after

**Comment by DaMatrix** [comment]
@dktapps Thanks, i have other things that i do other than trace down code for a minor annoyance that some players on my server are having.

**Comment by Creeperface01** [comment]
Yes raknet disconnects player so we dont have to do this somewhere else

**Comment by FilleDev** [comment]
What if you have disabled server's raknet? ;D

**Comment by tarik02** [comment]
@dktapps, if client is disconnected without notification(crash), it will stay in server if this will be removed from genisys. So this can be removed from nemisys... sorry.

**Comment by SleepSpace9** [comment]
@Tarik02 you probably mean "...So this can **not** be removed from nemisys." ? 
If so this was also my thought.

**Comment by Creeperface01** [comment]
@file14 then player can not join.... So you can not disable raknet

**Comment by tarik02** [comment]
@Creeperface01, we can disable raknet when enabled synapse.

**Comment by dktapps** [comment]
@DaMatrix Why the thumbs-down? I was genuinely thanking you.

**Comment by Creeperface01** [comment]
@tarik02 this is nemisys not genisys

**Comment by Creeperface01** [comment]
You can not disable raknet in nemisys

**Pull request merged**
