### PR TITLE
Bump Protocol to 1.4.0

### PR DESCRIPTION
**Pull request by MisterSheeple**
First step in the process of updating this to 1.4. I will add the features that 1.4 added that the server lacks soon, for now it's just the protocol bump. I will update this post with a changelog of what I change soon. Do not merge this PR yet.

### CODE REVIEW

**Comment by SupremeMortal** [comment]
I'm sure you've been told plenty of times, but bumping the protocol doesn't just magically make the server work with the latest version.

**Comment by MisterSheeple** [comment]
@SupremeMortal If you would have read the whole post you would have seen that it's just temporary. I'm going to update the PR with more features that were added in the 1.4 update, but it's just a protocol bump for now, and shouldn't be merged yet.

**Comment by MisterSheeple** [comment]
Closing this because after trying to port some code over from Nukkit, this repo appears to be missing a lot, so I don't think it's possible to update it to 1.4 without putting in updates that it doesn't have yet. This repo hasn't been updated since October 2017, and I'm really busy, and I don't see any point of updating it now that there's Nukkit, so unfortunately I can't give it the updates it needs, but if anyone else wants to, feel free.

**Comment by SupremeMortal** [comment]
https://github.com/NukkitX/Nemisys

**Pull request closed without merging**
