### PR TITLE
Version update to 0.15.10

### PR DESCRIPTION
**Pull request by jarne**

### CODE REVIEW

**Comment by Creeperface01** [comment]
@ishitatsuyuki ?

**Comment by ishitatsuyuki** [comment]
@Creeperface01 no spam pinging.

**Comment by legoboy0215** [comment]
Why wasn't this merged?

**Comment by boybook** [comment]
Have been updated in https://github.com/iTXTech/Nemisys/commit/7eec852f7a4dac159aed2e213de6f71876f0da1b

**Pull request closed without merging**
